### ISSUE TITLE
Unicode conversion problems with the new console

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#77] opened 2020-05-18 17:09 UTC
**Description**
Errors in processing unicode characters is preventing any runs on Windows machines.

**To Reproduce**
An example command was as follows:
<pre>metawards -d ncov -o test --force-overwrite-output --input data\metawards\initial_ensemble\inputs\disease.csv -a ExtraSeedsLondon.dat --repeats 1 --extractor uq4covid\model_config\metawards\only_i_per_ward -u uq4covid\model_config\metawards\lockdown_states.txt --iterator uq4covid\model_config\metawards\iterate</pre>

**Screenshots**
![uni1](https://user-images.githubusercontent.com/8965253/82240389-41d34200-9932-11ea-8fde-faf6a66ea7f4.png)

See also:

![uni2](https://user-images.githubusercontent.com/8965253/82240522-77782b00-9932-11ea-8264-c1a86fd97546.png)

**Environment:**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version: Metawards 0.10.0+186.g84f8f19 (Latest devel pull)

**Additional context**
Windows default is usually UTF16

**Comment by chryswoods** [comment] 2020-05-18 18:56
Thanks - I am surprised by this as this runs well on the Windows 10 Github actions runners (https://github.com/metawards/MetaWards/runs/685596309?check_suite_focus=true).

I’ve read through the Windows CMD docs and it seems they added support for UTF8 in 2018 (https://devblogs.microsoft.com/commandline/windows-command-line-unicode-and-utf-8-output-text-buffer/). The error picture suggests it may be the emoji I’m rendering in the spinner that is the issue.

Could you try again with “—theme simple” to see if that works? This uses an ascii spinner and almost no colour.

**Comment by fentonscode** [comment] 2020-05-18 19:00
I don't seem to be able to use that command at all

<pre>PS C:\CovidSims\Forks> metawards -d lurgy -o test --theme simple
usage: metawards [-h] [--version] [-c CONFIG] [-i INPUT]
                 [-l [LINE [LINE ...]]] [-r [REPEATS [REPEATS ...]]] [-s SEED]
                 [-a [ADDITIONAL [ADDITIONAL ...]]] [-o OUTPUT] [-d DISEASE]
                 [-m MODEL] [-D DEMOGRAPHICS] [--start-date START_DATE]
                 [--start-day START_DAY] [-p PARAMETERS] [-R REPOSITORY]
                 [-P POPULATION] [-n NSTEPS] [-u USER_VARIABLES]
                 [--iterator ITERATOR] [--extractor EXTRACTOR] [--mixer MIXER]
                 [--mover MOVER] [--UV UV] [--nthreads NTHREADS]
                 [--nprocs NPROCS] [--hostfile HOSTFILE]
                 [--cores-per-node CORES_PER_NODE] [--auto-bzip]
                 [--no-auto-bzip] [--force-overwrite-output]
                 [--max-nodes MAX_NODES] [--max-links MAX_LINKS] [--profile]
                 [--no-profile] [--mpi] [--scoop]
metawards: error: unrecognized arguments: --theme simple
PS C:\CovidSims\Forks> metawards -d lurgy -o test -theme simple
usage: metawards [-h] [--version] [-c CONFIG] [-i INPUT]
                 [-l [LINE [LINE ...]]] [-r [REPEATS [REPEATS ...]]] [-s SEED]
                 [-a [ADDITIONAL [ADDITIONAL ...]]] [-o OUTPUT] [-d DISEASE]
                 [-m MODEL] [-D DEMOGRAPHICS] [--start-date START_DATE]
                 [--start-day START_DAY] [-p PARAMETERS] [-R REPOSITORY]
                 [-P POPULATION] [-n NSTEPS] [-u USER_VARIABLES]
                 [--iterator ITERATOR] [--extractor EXTRACTOR] [--mixer MIXER]
                 [--mover MOVER] [--UV UV] [--nthreads NTHREADS]
                 [--nprocs NPROCS] [--hostfile HOSTFILE]
                 [--cores-per-node CORES_PER_NODE] [--auto-bzip]
                 [--no-auto-bzip] [--force-overwrite-output]
                 [--max-nodes MAX_NODES] [--max-links MAX_LINKS] [--profile]
                 [--no-profile] [--mpi] [--scoop]
metawards: error: unrecognized arguments: -theme simple</pre>

**Comment by fentonscode** [comment] 2020-05-18 19:02
P.S.: The unicode support is normally absolutely fine on Window (usually better there than other OSs) but occasionally additional Byte-Order-Marks (BOMs) or invalid code-points can be parsed. It might be an invalid byte sequence or character somewhere?

**Comment by chryswoods** [comment] 2020-05-18 19:11
Could you git clone directly from https://github.com/metawards/MetaWards as you aren’t running the latest version. Latest devel and master have the “—theme” option and are on version 0.12.0 now. Your fork on github I think is somehow out of date.

**Comment by chryswoods** [comment] 2020-05-18 19:12
The error is almost certainly the emoji. The document I linked says that emojis aren’t yet supported. 

The weird output in the header is because windows cmd doesn’t recognise the terminal hyperlink characters.

**Comment by fentonscode** [comment] 2020-05-19 07:06
Update: testing with `--theme simple` on version 0.12.0 still gives the same error

**Comment by chryswoods** [comment] 2020-05-19 07:13
Thanks - looking deeper it may be the actual write of the console output to a file. Guess now is that I’ve mistakenly opened the file in text rather than binary mode. Strange that this wasn’t picked up when the files were written in the CI. I’ll know more once I debug on a Windows box.

**Comment by chryswoods** [comment] 2020-05-19 07:14
(this is why you’ve been so helpful patiently finding and reporting these issues - CI can only do so much)

**Comment by chryswoods** [comment] 2020-05-19 09:27
I've made the changes that I think will work (couldn't get access to a windows box to check and debug). This is in the attached pull request. Once it's checked, I'll merge in, which will automatically close this issue. Please feel free to re-open if there is still a problem.

**Comment by fentonscode** [comment] 2020-05-19 12:49
![uni1](https://user-images.githubusercontent.com/8965253/82328196-74834600-99d7-11ea-9a66-3f721e0abfaa.png)

FYI: There's some odd chars still in the completed run message

**Comment by chryswoods** [comment] 2020-05-19 13:09
Those are the emojis. I'll disable them. The one on the right is a green tick or red cross depending on whether or not that run succeeded. The one on the left is perplexing as there shouldn't be anything printed there. My guess is that it is something left behind by the spinner.

<img width="1280" alt="Screenshot 2020-05-19 at 14 07 47" src="https://user-images.githubusercontent.com/3694698/82330099-4b17e980-99da-11ea-929b-d320d905ac60.png">

**Comment by fentonscode** [comment] 2020-05-19 13:16
Possibly this? See "Cursor Visibility" item 4 [here](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)

**Comment by chryswoods** [comment] 2020-05-19 15:47
Yes, it could be that character. This is likely a bug in yaspin, possibly caused by the emoji. I've removed emojis from windows in the linked pull request, and have also added a "--no-spinner" option to disable the spinner if it causes issues. Accepting will close this issue automatically. If there is still an extra character then I will debug another time once I get a windows box sorted out. Thanks for your help with this issue and your patience :-)

**Closed** 2020-05-19 15:56 UTC
Labels: bug
