### ISSUE TITLE
Option to suppress model intermediate console output

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#79] opened 2020-05-19 11:35 UTC
**Problem**
The new console printing is significantly slowing runs by printing extra per-iteration information to the Windows console (before it was only a summary output + user print commands in custom functions). This might also cause errors if any of the worker threads need access to the console output as one thread could trigger a flush with the amount of information now printing.

**Requested solution**
A command switch to turn the console back to previous revisions / no additional output (although still allow printing from within iterator code as before)

**Comment by chryswoods** [comment] 2020-05-19 11:55
The new version just reformats the data that was already being printed - it hasn't added any extra information. Also, printing only comes from a single thread so there is no problem with flushing. The threading model is that each metawards process has a single python thread, from which all printing is performed, and then nthreads openmp threads which are only used in cython and which do not print.

What you may be seeing is lots of printing from several metawards processes. The multiple processes (nprocs) are used to run multiple runs at the same time, e.g. via multiprocessing, scoop or mpi4py. These are launched with their output redirected to an output file, so not writing to the console. However, to do this, (and what has changed now) you have to use the console object to print.

Please change your iterator from;

```python
 
def my_iterator(**kwargs):
    print("Something...")
```

to 

```python
from metawards.utils import Console

def my_iterator(**kwargs):
    Console.print("Something...")
```

This will send your output to the right place, e.g. to the output.txt file in the directory for that run, or to the console if there is only one process and one run.

**Comment by chryswoods** [comment] 2020-05-19 11:56
(I am in the process of updating the tutorial to mention this - also, as you can see in Console, you can do more than just print. There are rulers, warnings, errors, panels and even markdown support)

**Comment by fentonscode** [comment] 2020-05-19 12:07
In terms of additional printing, there is a progress arrow that repeatedly spans the screen and is counting for nearly all of the in-run printing slowdown. I will change our printing statements to Console.print() and see what happens,

**Comment by chryswoods** [comment] 2020-05-19 12:17
Yes, that's the spinner to show that the code has not crashed. This only prints to the console and does not go into any output files. The new print system makes sure that all outputs are properly recorded to files, even if they are printed to the screen (some were lost in older versions of the code, particularly before the "output" directory was created - now everything will either be in output/console.log.bz2 or in one of the output.txt.bz2 files produced for each run).

**Comment by fentonscode** [comment] 2020-05-19 12:19
I'd like a spinner, but could it use \r to prevent extending the console? A bit like a progress bar affair?

**Comment by chryswoods** [comment] 2020-05-19 12:27
The spinner does know the width of the console, so should be sizing itself properly, e.g.

https://github.com/metawards/MetaWards/blob/8b45008b7ea0499d6b42118ddf40fec485ce08e1/src/metawards/utils/_console.py#L228

and for the simple theme

https://github.com/metawards/MetaWards/blob/8b45008b7ea0499d6b42118ddf40fec485ce08e1/src/metawards/themes/_simple.py#L64

The spinner is just a [yaspin](https://pypi.org/project/yaspin/) spinner, which is meant to be windows safe.

That is isn't indicates something is not right. Could you have a play with the spinner code and see if you can get it working on windows. I don't have access to windows so it is really difficult to debug this.

**Comment by fentonscode** [comment] 2020-05-19 12:37
It's working properly now, I think yaspin suffers from the same issue as many others - which is if there is a print statement in between an update it duplicates the spinner on the next line rather than tracking where the spinner is and moving it back down to the bottom (not easy, but I probably have code somewhere which 'pins' the progress item to the bottom of the console in C).

**Comment by fentonscode** [comment] 2020-05-19 12:58
![uni1](https://user-images.githubusercontent.com/8965253/82329090-afd24480-99d8-11ea-9bdf-c1b6b0935bb4.png)

Spoke too soon: It appears when doing repeats, sending things to Console.print is not doing the same thing

**Comment by chryswoods** [comment] 2020-05-19 13:05
Is your "Sending I per ward to the output stream" being printed "print" or "Console.print"? Could you post your extractor code here?

**Comment by fentonscode** [comment] 2020-05-19 13:09
Extractor is [here](https://github.com/fentonscode/uq4covid/blob/master/model_config/metawards/only_i_per_ward.py) - I might have missed one somewhere (NOTE Line 51 is redundant).

**Comment by chryswoods** [comment] 2020-05-19 13:44
I've just completed 200 runs and it prints correctly using your extractor. It is strange in your output that it starts mis-printing from the 15th model run and not before. Does the rest of the output for iterations above 15 go to the right place (e.g. directory/output.txt.bz2 should contain all Console.print output for a model run). Do you see the "Sending I per ward" printed in directory/output.txt.bz2 in the first 14 runs?

Also, your extractor looks good. I took a look at the iterator too and see that you are using the "rate" method from the tutorial to implement the lockdown. This is ok. Leon prefers to run lockdowns by changing scale_uv (thereby changing the FOI calculation - in contrast the rate uses the same FOI but scales it down to reduce the rate). An example using scale_uv is in the example directory - https://github.com/metawards/MetaWards/blob/devel/examples/lockdown/lockdown.py

Note that because the parameter is changing, it only needs changing in the iterate_lockdown function. The same advance functions are called. The lockdown example in that directory completely reproduces the lockdown model implemented in the original C code.

**Comment by fentonscode** [comment] 2020-05-19 14:24
Our iterator is [here](https://github.com/fentonscode/uq4covid/blob/master/model_config/metawards/iterate.py) for reference. I don't see the Console.print() output for the first runs at all. We are currently in a meeting about this now, so I might point people to this post if changing `scale_uv` is better. With reference to the last point, is our iterator compliant? It appears to do a two-stage rate calculation as we expect it.

**Comment by chryswoods** [comment] 2020-05-19 14:44
Yes, your iterator is compliant and doing the right thing. We think both ways are mathematically similar (one is multiplying the parts that sum up to the foi, while the other is post-multiplying the foi by a factor). My view as a Monte Carlo rate person is that scaling down the rate was more intuitive, while Leon preferred scaling down scale_uv as this was more directly related to R_0.

Useful to know that the Console.print() outputs from the iterator have gone missing. For now, I suggest commenting out the print line as it is not needed and is causing issues. I'll look into this once I get hold of a windows box. The Console.print in the extractor is identical to the other Console.prints that give output during a run, so I need to work out what has subtly changed when the Console.print is called from a function that has been loaded - and where the other print outs have gone ;-)

**Comment by fentonscode** [comment] 2020-05-19 16:09
No problem, I was using it to make sure my user vars were being picked up and that the date format was working. Mainly as I was lazily debugging iterators and extractors by just doing a quick run - might be worth adding a debugging harness to the tutorials. I was OK editing the Python code in Notepad, but it wasn't 'good' practice. I assume there's something I can use in the tests folder?

**Comment by chryswoods** [comment] 2020-05-19 16:35
I use printf debugging a lot too - which makes me think I should add a "Console.debug" function to make this easier ;-)

Lately I've been trying to be "professional" and use the debugger built into vscode. pytest is fully integrated, so I can run the tests from within vscode and step through and see variables, set breakpoints etc there. A good tutorial for this is here https://code.visualstudio.com/docs/python/python-tutorial

**Comment by fentonscode** [comment] 2020-05-19 17:17
I was mainly getting at having a minimal harness for having a network/population/workspace surrogate available to test the functionality. Have you ever used other Python IDEs? I really want to use VSCode again but I cannot deal with the x2/x3 slowdown by running in it. Even with cached symbols and sources I cannot come anywhere near running from a cmd python prompt or PyCharm

**Comment by chryswoods** [comment] 2020-05-19 17:28
For interactive testing I tend to use ipython or jupyter notebooks. I use pytest fixtures to re-use slow-to-load objects, and mock for mocking (not needed yet in metawards, though likely soon).

I’ve not used another python IDE - my pathway through IDEs went via vim, kate, kdevelop, Xcode and now vscode. I do like the look of the live testing view in pycharm, but am now pretty wedded to vscode as I use lots of languages across the projects and don’t want to jump between IDEs.

I’m happy to add things that would help debugging with pycharm - just ask :-)

**Comment by fentonscode** [comment] 2020-05-19 17:37
I normally have a VS-centric environment with PyCharm for Python that's going to take a while to run. PyCharm can be loaded into a debugging state or test state from the command line with a bit of shell magic in VS.

**Comment by chryswoods** [comment] 2020-05-20 16:18
I've now got Windows 10 in the VM and can test that locally. I've also added `Console.debug` for printing that you use to check things. This includes printing variables out in a nice table if desired (passed as a list to the `variables` keyword argument). Full instructions on how to use it and how to set debug levels is [here](https://metawards.org/versions/devel/devsupport.html#printf-debugging)

**Comment by chryswoods** [comment] 2020-05-21 11:06
I'm going to close this as I think that the move to double-check encodings of files, and the various re-encodings if errors are raised should have fixed this. If the error persists we can track it down in a new issue.

**Closed by chryswoods** 2020-05-21 11:06 UTC
Labels: enhancement
